language: node_js
node_js: stable
dist: trusty
sudo: required
group: edge
addons:
  firefox: latest
  # sauce_connect: true
  chrome: stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g polymer-cli
- polymer install
- polymer lint
script:
- xvfb-run polymer test
# - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin local; fi
env:
  global:
    secure: QKLQ8BsExhSHA6IKDoDQTzmitxy2bWrHneEM8BA7wzorFKOtSiPlNE8ketXc/2k5zN6L59eqJP/o/kG08awsjU07KlYWkZtE8UPr/9RWTx+xDgZ6KqqaFmuQ+vgYjHuSD263gZYkMGnDOolFAtpabeXyLpQQRmhxSvzwwNrha+Vcq+e+3Qf7f1UpJSOo2QO97Yn8DnLsXPAlDMV8Q7rS8id4ny6+MQys2nT5HMBR4MzN1RCuWMwKqnS5tt9m73KrAnH7TgZ8j4DmUoX6lOFFA9DUykRqagRlERDdUcE9xUXiJfWW8+lbmR+13GI0l4ImaMc4lUs9BKpkd/quCHyfrwKHj0bJjeMCRg6WaxE/ZVqJ2WZSgaSU8LV4wKuQWAbiMIKVeGgZ/RatlGRzZs4c7so276vYseZHSulrAHWDD/A5jcrqJo4CSO9s6vktx3Wl6yFv4JsKKFH/bJMRdyA8P5lSPjNvbmxFMnP1oDwP4GfO+XOLKDF3Zprj0RzbONCRrFUGXyaOLrdc1Rc6uZm+FPD/Mf2H4BJs73xAKwa9aGbF1vDMVSyiPIAD49U99l7ffQRlyY3HGegksKQ7TjZ7vbzK8Z/QlQQGufKeNAzryF9e6vDq6TdgEXDoEJgpTVOdNG8m4NTPSagEnF+CNyOfDaemPqon12/shg+ZwMVDqg4=
deploy:
  provider: npm
  email: info@migueldelmazo.com
  api_key:
    secure: qzDarJ98sQTs3QdfDcbF44KM6zB3LHFVm2Avn9ppRPe7inAS4KSGPmUkvcu+Khmtjyfi7+RcVFogXDcGb69dXHRv4tNGmsFqHC/mf7h15o8fVKh38ztZLy+VxhPsXfdf3cPzXaEaoGCwtee6oQ5oaQmza75+ffMTqKIXLGqMNIiR1CM0pgFgSZBnuYh46gVKXNZjSgmijReMstsudWur9OI5/sEoyWruepnJ5UUVEZaIJUUxP3m8Rq5dfdHMhCQ0Q/WZrFdHjasUPNaUQyQ4lKwC7RJBpoUK4GsuxfhPNUWC4p8lbrm+/t2fZglXn7XeMHt2PWqkXpSqMLOham2aRqPQHKkJTyHWDJWnRG+kctA6EM6FFnfIPj6OJlvLdQyKNt2nP/+XoXowtfc9aixKeKs27U5iUScQ9uOicAQi6NQm5vIYsCfsJNbyCKKMkpHzcqrX5rlL/VNiVUsMgirUFzCUo8RzddOHoeUj+0nXrnaglRwoWYyGxxx3j7OYWrju7CECiM1ty4d16zaBEA0DZ0h0XiYx85KhCnHygLds889/KvSAaqzPpZdu7zU1eqXXCLUukL5dQTdqM6+O5yDzp4xAUvEtkm07BnEVHWh7aOHk9ioRRARRxOQvWV26Z0E7e7yTddlewU9BTDwDSrevI5eXfZS2BXzMU93n00rWWyc=
  on:
    branch: master
    tags: true
    repo: TherapyChat/rss-items
